-- Epic #298 — Code Discovery foundation.
-- Closes #306 (CodeGraph data model) and #309 (Finding confidence + derivation).
--
-- Three new tables: code_graphs, code_symbols, code_edges.
-- Two new columns + a nullable FK on findings.
--
-- Backfill rule (per #309): every existing Finding row was generated by an
-- analysis agent before this work, so derivation='inferred', confidence=0.7.
-- The DEFAULT clauses below cover both new inserts on legacy code paths and
-- ALTER TABLE backfill in a single statement on SQLite.

-- ----------------------------------------------------------------------------
-- Finding provenance columns (#309)
-- ----------------------------------------------------------------------------
-- NOTE: derivation, confidence, and symbolId columns + indexes are already
-- present on "findings" after 20260430145720_epic_396_speckit_features which
-- rebuilds the table with those columns. The ALTER TABLE statements that were
-- here originally are therefore no-ops and have been removed to prevent
-- "duplicate column name" errors on fresh deploys.

-- ----------------------------------------------------------------------------
-- CodeGraph (#306)
-- ----------------------------------------------------------------------------
CREATE TABLE "code_graphs" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "repoConnectionId" TEXT,
    "commitSha" TEXT,
    "symbolCount" INTEGER NOT NULL DEFAULT 0,
    "edgeCount" INTEGER NOT NULL DEFAULT 0,
    "languageStats" TEXT NOT NULL DEFAULT '{}',
    "lastIndexedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "code_graphs_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "code_graphs_repoConnectionId_fkey" FOREIGN KEY ("repoConnectionId") REFERENCES "repo_connections" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE UNIQUE INDEX "code_graphs_projectId_repoConnectionId_key" ON "code_graphs"("projectId", "repoConnectionId");
CREATE INDEX "code_graphs_projectId_idx" ON "code_graphs"("projectId");

-- ----------------------------------------------------------------------------
-- CodeSymbol (#306)
-- ----------------------------------------------------------------------------
CREATE TABLE "code_symbols" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "codeGraphId" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "qualifiedName" TEXT NOT NULL,
    "filePath" TEXT NOT NULL,
    "startLine" INTEGER NOT NULL,
    "endLine" INTEGER NOT NULL,
    "language" TEXT NOT NULL,
    "contentHash" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "code_symbols_codeGraphId_fkey" FOREIGN KEY ("codeGraphId") REFERENCES "code_graphs" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "code_symbols_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX "code_symbols_projectId_kind_idx" ON "code_symbols"("projectId", "kind");
CREATE INDEX "code_symbols_projectId_qualifiedName_idx" ON "code_symbols"("projectId", "qualifiedName");
CREATE INDEX "code_symbols_codeGraphId_filePath_idx" ON "code_symbols"("codeGraphId", "filePath");

-- ----------------------------------------------------------------------------
-- CodeEdge (#306)
-- ----------------------------------------------------------------------------
CREATE TABLE "code_edges" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "codeGraphId" TEXT NOT NULL,
    "projectId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "fromSymbolId" TEXT NOT NULL,
    "toSymbolId" TEXT,
    "toQualifiedName" TEXT,
    "filePath" TEXT NOT NULL,
    "line" INTEGER NOT NULL,
    "metadata" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "code_edges_codeGraphId_fkey" FOREIGN KEY ("codeGraphId") REFERENCES "code_graphs" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "code_edges_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "projects" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "code_edges_fromSymbolId_fkey" FOREIGN KEY ("fromSymbolId") REFERENCES "code_symbols" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "code_edges_toSymbolId_fkey" FOREIGN KEY ("toSymbolId") REFERENCES "code_symbols" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX "code_edges_fromSymbolId_kind_idx" ON "code_edges"("fromSymbolId", "kind");
CREATE INDEX "code_edges_toSymbolId_kind_idx" ON "code_edges"("toSymbolId", "kind");
CREATE INDEX "code_edges_projectId_kind_idx" ON "code_edges"("projectId", "kind");
CREATE INDEX "code_edges_codeGraphId_filePath_idx" ON "code_edges"("codeGraphId", "filePath");

-- ----------------------------------------------------------------------------
-- Finding -> CodeSymbol FK (deferred until code_symbols exists)
-- ----------------------------------------------------------------------------
-- SQLite cannot ADD CONSTRAINT after the fact. Prisma's migrate engine treats
-- this column-only addition with no FK-introspection at the SQL layer; the FK
-- relationship lives in the Prisma client model. The Postgres twin enforces
-- the FK at the DB layer. This is acceptable per the existing schema strategy
-- (see other nullable cross-model columns in this codebase).
