/*
 * This file is generated by jOOQ.
 */
package org.jooq.example.db.public_.tables;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

public class Book extends TableImpl<BookRecord> {

    private static final long serialVersionUID = 1L;

    public static final Book BOOK = new Book();

    public final TableField<BookRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    public final TableField<BookRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR, this, "");

    private Book(Name alias, Table<BookRecord> aliased) {
        this(alias, aliased, null);
    }

    private Book(Name alias, Table<BookRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public Book(String alias) {
        this(DSL.name(alias), BOOK);
    }

    public Book(Name alias) {
        this(alias, BOOK);
    }

    public Book() {
        this(DSL.name("book"), null);
    }
}
