/*
 * This file is generated by jOOQ.
 */
package org.jooq.example.db.public_;

import org.jooq.example.db.public_.tables.Book;

public class Tables {

    public static final Book BOOK = Book.BOOK;
}
