"use client";

/**
 * Clarification Dialog Component (Epic #597 / Issue #625).
 *
 * Interactive Q&A interface that lets users answer clarifying questions
 * generated by the requirements enhancement pipeline.
 */
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { useAppMutation } from "@/lib/use-app-mutation";
import {
  analysisApi,
  type ClarificationStatePayload,
  type ClarifyingQuestion,
  type ClarifyImportResult,
} from "@/lib/analysis-api";
import { triggerDownload } from "@/lib/plugins-api";
import { formatSourceLabel } from "@/lib/format-source-label";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

/**
 * Issue #1104 (finding C) — read-only Q&A transcript of every answered round.
 * Answers come from the question's own `answer` field, falling back to the
 * round's `answers[]` for rounds persisted before the server stamped them.
 */
export function AnsweredRounds({
  state,
}: {
  state: ClarificationStatePayload;
}): React.ReactElement | null {
  const rounds = state.rounds
    .map((round) => {
      // Rounds persisted by older builds may carry neither array.
      const byId = new Map((round.answers ?? []).map((a) => [a.questionId, a.answer]));
      const answered = (round.questions ?? [])
        .map((q) => ({ ...q, submitted: q.answer ?? byId.get(q.id) }))
        .filter((q) => (q.submitted ?? "").trim().length > 0);
      return { round: round.round, answered };
    })
    .filter((r) => r.answered.length > 0);

  if (rounds.length === 0) return null;

  return (
    <div className="space-y-3" data-testid="answered-rounds">
      {rounds.map((r) => (
        <div key={r.round} className="space-y-2">
          <p className="text-xs font-medium uppercase tracking-wide text-zinc-500">
            Round {r.round} — {r.answered.length} answered
          </p>
          {r.answered.map((q) => (
            <div key={q.id} className="rounded border border-zinc-800 p-3">
              <p className="text-sm font-medium text-zinc-200">{q.question}</p>
              <p className="mt-1 text-sm text-zinc-400">{q.submitted}</p>
            </div>
          ))}
        </div>
      ))}
    </div>
  );
}

interface ClarificationDialogProps {
  projectId: string;
  analysisId: string;
  state: ClarificationStatePayload;
  onComplete: () => void;
}

export function ClarificationDialogPanel({
  projectId,
  analysisId,
  state,
  onComplete,
}: ClarificationDialogProps): React.ReactElement {
  const currentRound = state.rounds[state.rounds.length - 1];
  const questions = currentRound?.questions ?? [];

  // Self-resolution: pre-fill grounded/partial questions with the server's
  // suggested answer so the human confirms (or edits) rather than re-typing.
  // Open questions start blank. Keyed on the question set so a new round/state
  // re-seeds the pre-filled answers.
  const seedAnswers = (): Record<string, string> => {
    const seed: Record<string, string> = {};
    const submitted = new Map((currentRound?.answers ?? []).map((a) => [a.questionId, a.answer]));
    for (const q of questions) {
      // Issue #1104 (finding C) — an answer the user already submitted wins over
      // the grounded suggestion; re-opening a round must never blank their work.
      const prior = q.answer ?? submitted.get(q.id);
      if (prior) {
        seed[q.id] = prior;
      } else if (
        (q.groundingStatus === "grounded" || q.groundingStatus === "partial") &&
        q.groundedAnswer
      ) {
        seed[q.id] = q.groundedAnswer;
      }
    }
    return seed;
  };
  const [answers, setAnswers] = useState<Record<string, string>>(seedAnswers);

  // Issue #1117 (finding D) — re-seed when the PERSISTED ANSWERS change, not
  // only when the question set does.
  //
  // The reported symptom was a transient "0 of 14 answered" with blank inputs
  // straight after Submit, while the server already held all 14. The cause was a
  // two-part race: `onSuccess` cleared local state synchronously, and this
  // effect keyed on question ids alone — so if the refetch came back with the
  // same round (which is the normal case), nothing re-seeded and the form stayed
  // empty until a full reload. Right after #1104/#1116 fixed real answer loss on
  // this exact screen, that reads as the bug coming back.
  const questionKey = questions
    .map((q) => `${q.id}=${(q.answer ?? "").length}`)
    .concat((currentRound?.answers ?? []).map((a) => `${a.questionId}=${a.answer.length}`))
    .join("|");
  useEffect(() => {
    setAnswers(seedAnswers());
  }, [questionKey]);

  // Epic #201 (#213) — when resuming a persisted dialog, surface which
  // ambiguities are already addressed vs. still remaining in this round.
  //
  // Issue #1117 (finding A) — "remaining" is now measured against everything
  // ADDRESSED (answered by the user OR closed by the resolution model), not
  // against the model's tally alone. The reported run answered 14 questions and
  // read "1 resolved / 13 remaining", which told the user their work had not
  // taken when in fact all 14 answers had persisted.
  const answeredCount = Object.values(answers).filter((a) => a.trim().length > 0).length;
  const addressedFields = new Set([
    ...state.resolvedAmbiguities,
    ...(state.answeredAmbiguities ?? []),
  ]);
  const remainingFields = questions
    .map((q) => `${q.requirementId}:${q.ambiguityField}`)
    .filter((key) => !addressedFields.has(key));
  const addressedCount = addressedFields.size;
  /** What the resolution model claimed — reported separately, never as progress. */
  const modelConfirmedCount = state.resolvedAmbiguities.length;

  // #241 — clarification submit: success/error toasts + pending button state.
  //
  // Issue #1104 (finding C) — the submit response is `{ state, … }`, so the old
  // `result.completed` read was ALWAYS undefined: the panel never refetched and
  // kept rendering the pre-submit round ("0 resolved / 12 remaining") as though
  // the answers had gone nowhere. Refresh on every successful submit.
  const submitMutation = useAppMutation({
    mutationFn: () =>
      analysisApi.submitClarifyAnswers(
        projectId,
        analysisId,
        Object.entries(answers).map(([questionId, answer]) => ({ questionId, answer })),
      ),
    successMessage: (result) =>
      result.state?.completed ? "Clarification complete" : "Answers submitted",
    errorMessage: "Failed to submit answers",
    // Issue #1117 (finding D) — do NOT clear the answers here. `onComplete()`
    // only *starts* a refetch; blanking local state in the same tick guaranteed
    // a window where the panel showed nothing while the server held everything.
    // The re-seed effect above now takes the refetched state, so a new round
    // arrives with fresh (empty) inputs and a re-rendered current round keeps
    // the user's text on screen throughout.
    onSuccess: () => {
      onComplete();
    },
  });

  // Business Analyst CSV round-trip: export the current round's questions,
  // answer offline, re-import. Import applies answers via the existing submit
  // path server-side, so a successful import refreshes the dialog (onComplete).
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [importSummary, setImportSummary] = useState<ClarifyImportResult | null>(null);

  const exportMutation = useAppMutation({
    mutationFn: () => analysisApi.exportClarifyCsv(projectId, analysisId),
    successMessage: "Questions exported",
    errorMessage: "Failed to export questions",
    onSuccess: ({ blob, filename }) => {
      triggerDownload(blob, filename);
    },
  });

  const importMutation = useAppMutation({
    mutationFn: (file: File) => analysisApi.importClarifyAnswers(projectId, analysisId, file),
    successMessage: (result) =>
      `Imported ${result.applied} answer(s)` +
      (result.unmatched.length > 0 ? ` — ${result.unmatched.length} unmatched` : ""),
    errorMessage: false, // surface the raw thrown message verbatim (below).
    onSuccess: (result) => {
      setImportSummary(result);
      onComplete();
    },
    onError: (error) => {
      const message = error instanceof Error ? error.message : "Failed to import answers";
      toast.error(message);
    },
  });

  const onFilePicked = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    // Reset so picking the same file twice still fires onChange.
    e.target.value = "";
    if (file) {
      importMutation.mutate(file);
    }
  };

  const csvActions = (
    <div className="flex items-center gap-2">
      <Button
        variant="outline"
        size="sm"
        onClick={() => exportMutation.mutate()}
        disabled={exportMutation.isPending}
      >
        {exportMutation.isPending ? "Exporting…" : "Export questions"}
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={() => fileInputRef.current?.click()}
        disabled={importMutation.isPending}
      >
        {importMutation.isPending ? "Importing…" : "Import answers"}
      </Button>
      <input
        ref={fileInputRef}
        type="file"
        accept=".csv"
        className="hidden"
        data-testid="clarify-import-input"
        onChange={onFilePicked}
      />
    </div>
  );

  if (state.completed) {
    return (
      <Card className="space-y-3 p-4" data-testid="clarification-complete">
        <div className="flex items-center gap-2">
          <span className="text-emerald-400">✓</span>
          <h3 className="font-semibold">Clarification Complete</h3>
        </div>
        {/* Issue #1117 (finding A) — lead with what the USER did. The old line
            reported the resolution model's tally ("1 ambiguities resolved")
            after fourteen substantive answers, which reads as thirteen answers
            having been thrown away. */}
        <p className="text-sm text-zinc-400">
          {addressedCount} ambiguit{addressedCount === 1 ? "y" : "ies"} addressed across{" "}
          {state.rounds.length} round(s).
          {state.escalatedToSonnet && (
            <span className="ml-1 text-amber-400">
              (Escalated to Sonnet for complex resolution)
            </span>
          )}
        </p>
        {modelConfirmedCount < addressedCount && (
          <p className="text-xs text-zinc-500" data-testid="clarification-model-confirmed">
            METIS confirmed {modelConfirmedCount} of these as fully resolved. The rest are recorded
            from your answers and carried into the analysis either way — no answer was discarded.
          </p>
        )}
        {/* Issue #1104 (finding C) — the answers the user wrote are part of the
            analysis record, so show them. A bare "complete" summary is how a
            dozen hand-written answers became unreachable through the UI. */}
        <AnsweredRounds state={state} />
      </Card>
    );
  }

  return (
    <Card className="space-y-4 p-4">
      <div className="flex items-center justify-between gap-3">
        <h3 className="text-lg font-semibold">Clarifying Questions</h3>
        <div className="flex items-center gap-2">
          {csvActions}
          <span className="rounded border border-zinc-700 bg-zinc-800 px-2 py-0.5 text-xs text-zinc-400">
            Round {state.currentRound} / {state.maxRounds}
          </span>
        </div>
      </div>
      <p className="text-sm text-zinc-400">
        Please answer these questions to resolve requirement ambiguities. You can also export them
        to CSV, answer offline, and re-import the file.
      </p>

      {importSummary && (
        <p className="text-xs text-zinc-400" data-testid="clarify-import-summary">
          Imported {importSummary.applied} answer(s); {importSummary.skipped} skipped
          {importSummary.unmatched.length > 0 && (
            <> ; unmatched: {importSummary.unmatched.join(", ")}</>
          )}
          .
        </p>
      )}

      {/* Epic #201 (#213) — addressed vs remaining, rehydrated from persisted state. */}
      <div className="flex flex-wrap gap-2 text-xs" data-testid="clarification-progress">
        <span className="rounded bg-emerald-900/40 px-2 py-0.5 text-emerald-300">
          {addressedFields.size} addressed
        </span>
        <span className="rounded bg-amber-900/40 px-2 py-0.5 text-amber-300">
          {remainingFields.length} remaining
        </span>
        {/* Issue #1104 (finding C) — "0 resolved" said nothing about the twelve
            answers already submitted. Count them explicitly. */}
        <span className="rounded bg-zinc-800 px-2 py-0.5 text-zinc-300">
          {answeredCount} of {questions.length} answered
        </span>
      </div>

      <div className="space-y-4">
        {questions.map((q: ClarifyingQuestion) => {
          const grounded = q.groundingStatus === "grounded";
          const partial = q.groundingStatus === "partial";
          const isSelfResolved = grounded || partial;
          const sources = [
            ...new Set((q.groundingCitations ?? []).map((c) => c.source).filter(Boolean)),
          ];

          return (
            <div
              key={q.id}
              className="rounded border border-zinc-800 p-3"
              data-testid={isSelfResolved ? "grounded-question" : "open-question"}
            >
              <Label className="mb-1 block text-sm font-medium">{q.question}</Label>
              {q.context && <p className="mb-2 text-xs text-zinc-500">{q.context}</p>}

              {isSelfResolved && (
                <div className="mb-2 space-y-1">
                  <span
                    className={
                      grounded
                        ? "inline-block rounded bg-emerald-900/40 px-2 py-0.5 text-xs text-emerald-300"
                        : "inline-block rounded bg-amber-900/40 px-2 py-0.5 text-xs text-amber-300"
                    }
                    data-testid="grounding-badge"
                  >
                    {grounded
                      ? "Answered from project knowledge — confirm or edit"
                      : "Partially answered — review and complete"}
                  </span>
                  {sources.length > 0 && (
                    // #427 — render human-readable source labels (basename — repo)
                    // instead of raw `connector:repo:…` ids; keep the full raw ids
                    // in the tooltip for copy/deep-link.
                    <p
                      className="text-xs text-zinc-500"
                      data-testid="suggested-answer-source"
                      title={sources.join(", ")}
                    >
                      Suggested answer (from{" "}
                      {sources.map((s) => formatSourceLabel(s).label).join(", ")})
                    </p>
                  )}
                </div>
              )}

              <Input
                placeholder={
                  isSelfResolved ? "Confirm or edit the suggested answer…" : "Your answer..."
                }
                value={answers[q.id] ?? ""}
                onChange={(e) => setAnswers((prev) => ({ ...prev, [q.id]: e.target.value }))}
              />
            </div>
          );
        })}
      </div>

      <div className="flex items-center justify-between pt-2">
        {/* Issue #1117 (finding A) — count the user's own answers, not the
            resolution model's confirmations. */}
        <p className="text-xs text-zinc-500">
          {addressedCount} ambiguit{addressedCount === 1 ? "y" : "ies"} addressed so far
        </p>
        <Button
          onClick={() => submitMutation.mutate()}
          disabled={submitMutation.isPending || Object.values(answers).filter(Boolean).length === 0}
        >
          {submitMutation.isPending ? "Submitting…" : "Submit Answers"}
        </Button>
      </div>

      {submitMutation.isError && (
        <p className="text-sm text-red-400">Failed to submit answers. Please try again.</p>
      )}
    </Card>
  );
}
