/**
 * Spec Kit `constitution.md` generator (Issue #209 — Epic #193).
 *
 * Merges:
 *   1. Every `*.md` file under the ATTACHED WORKSPACE's `.github/instructions/`
 *      directory in deterministic alphabetical order (so the same checkout
 *      always produces the same constitution). The caller must supply the
 *      workspace root via `instructionsDir` — the generator never falls back
 *      to the METIS server's own `.github/instructions/` (those are internal
 *      Copilot/Claude dev-tool conventions, not end-user project governance).
 *   2. The project-level overrides written via `/specify` wizard or the
 *      `PUT /api/projects/:id/spec-kit/files/constitution.md` endpoint.
 *
 * The generated content is appended onto the existing `constitution.md`
 * artifact when the user has hand-edited the file (we never silently
 * stomp project overrides).
 */
import fs from "node:fs/promises";
import path from "node:path";
import { writeArtifact, getArtifact } from "./artifacts.js";

// No default instructions directory — callers must supply the attached workspace
// path explicitly. Falling back to process.cwd()/../.github/instructions would
// accidentally read METIS's own Copilot/Claude dev-tool convention files in
// development, leaking internal tooling conventions into end-user constitutions.
const NO_DEFAULT_DIR = "";

export interface GenerateConstitutionInput {
  projectId: string;
  /** Absolute path to the attached workspace's .github/instructions/ directory.
   *  Required for the constitution to include instruction files. When omitted,
   *  the generator produces a constitution with only the project-level overrides.
   */
  instructionsDir?: string;
  /** Override the directory reader (tests). */
  reader?: (dir: string) => Promise<InstructionFile[]>;
  /** Optional project-level overrides appended verbatim. */
  projectOverrides?: string;
  /** Forwarded to the artifact writer. */
  actorId?: string | null;
}

export interface InstructionFile {
  filename: string;
  content: string;
}

const HEADER = [
  "<!--",
  "  Generated by /specify constitution generator (Epic #193).",
  "  Edits to this file are preserved when re-running the generator UNLESS",
  "  the auto-managed sections (between BEGIN/END markers) are removed.",
  "-->",
  "",
  "# Project Constitution",
  "",
  "This document is the single source of truth for the agent fleet running",
  "inside this project. Every BA / Architect / PO / QA agent receives the",
  "rendered constitution as a system-level constraint before any other",
  "instructions in their prompt chain.",
  "",
].join("\n");

const AUTO_BEGIN = "<!-- BEGIN auto-managed: instruction files -->";
const AUTO_END = "<!-- END auto-managed: instruction files -->";
const OVERRIDES_BEGIN = "<!-- BEGIN auto-managed: project overrides -->";
const OVERRIDES_END = "<!-- END auto-managed: project overrides -->";

/** Default reader — lists every `*.md` under `dir` in alpha order. */
export async function defaultReader(dir: string): Promise<InstructionFile[]> {
  let entries: string[];
  try {
    entries = await fs.readdir(dir);
  } catch {
    return [];
  }
  const md = entries.filter((e) => e.toLowerCase().endsWith(".md")).sort();
  const out: InstructionFile[] = [];
  for (const filename of md) {
    try {
      const content = await fs.readFile(path.join(dir, filename), "utf8");
      out.push({ filename, content });
    } catch {
      // Skip unreadable files — never crash the generator over a single bad mode bit.
    }
  }
  return out;
}

/**
 * Build the constitution text. Pure — does not write to the DB. Useful
 * when callers want to preview before persisting.
 */
export function buildConstitution(files: InstructionFile[], projectOverrides?: string): string {
  const sections: string[] = [HEADER, AUTO_BEGIN, ""];
  for (const f of files) {
    sections.push(`## From \`.github/instructions/${f.filename}\``);
    sections.push("");
    sections.push(f.content.trim());
    sections.push("");
  }
  sections.push(AUTO_END, "");
  sections.push(OVERRIDES_BEGIN);
  if (projectOverrides && projectOverrides.trim().length > 0) {
    sections.push("");
    sections.push("## Project-level overrides");
    sections.push("");
    sections.push(projectOverrides.trim());
    sections.push("");
  }
  sections.push(OVERRIDES_END, "");
  return sections.join("\n");
}

export async function generateConstitution(input: GenerateConstitutionInput): Promise<string> {
  const dir = input.instructionsDir ?? NO_DEFAULT_DIR;
  const reader = input.reader ?? defaultReader;
  const files = await reader(dir);
  const content = buildConstitution(files, input.projectOverrides);
  await writeArtifact({
    projectId: input.projectId,
    name: "constitution.md",
    content,
    actorId: input.actorId,
  });
  return content;
}

/**
 * Returns the project's existing constitution content, or null when the
 * project hasn't run the wizard yet. The slash command dispatcher uses
 * this to decide whether to prepend the constitution to subsequent
 * agent system prompts.
 */
export async function readProjectConstitution(projectId: string): Promise<string | null> {
  const row = await getArtifact(projectId, "constitution.md");
  return row ? row.content : null;
}

/**
 * Returns true when the project has a constitution shorter than the
 * canonical placeholder produced by the wizard. The chat surface uses
 * this to gate the "Run /specify wizard?" CTA.
 */
export async function projectHasConstitution(projectId: string): Promise<boolean> {
  const content = await readProjectConstitution(projectId);
  return Boolean(content && content.trim().length > 0);
}

export const __TESTING__ = {
  AUTO_BEGIN,
  AUTO_END,
  OVERRIDES_BEGIN,
  OVERRIDES_END,
  HEADER,
};
