/**
 * GitHub test-case exporter (Epic #856, issue #876).
 *
 * Converts generated suggestions into `IssueDraft` rows and enqueues them
 * through the existing publishing pipeline (`createBatch` + `executeBatch`).
 *
 * Each draft gets:
 *   - `draftType = "task"`
 *   - `labels = ["type:test", ...suggestion.tags]`
 *   - `body` rendered from the test-case template (see
 *     `.github/ISSUE_TEMPLATE/test-case.md`) using GWT + acceptance criteria
 *   - `requirementId` linking back to the first mapped requirement (when
 *     present), enabling sub-issue parent linkage upstream.
 *
 * Dry-run short-circuits before the GitHub call and returns the rendered
 * drafts so the UI can preview them. Failures inside the publishing
 * pipeline propagate via the >50% rollback rule already enforced by
 * `runBatch`.
 */
import { prisma } from "../../prisma.js";
import { createBatch, executeBatch } from "../../publishing/publishing-service.js";
import type { CreatePublishBatchInput } from "@metis/shared";

import type { ExportableSuggestion } from "./types.js";

export interface GithubExportOptions {
  readonly projectId: string;
  readonly targetOwner: string;
  readonly targetRepo: string;
  readonly actorId: string;
  readonly secretRef?: string;
  readonly additionalLabels?: ReadonlyArray<string>;
  readonly milestone?: number;
  readonly dryRun?: boolean;
  readonly confirmCrossProject?: boolean;
}

export interface GithubExportResult {
  readonly batchId: string | null;
  readonly draftIds: ReadonlyArray<string>;
  readonly dryRun: boolean;
  readonly previews: ReadonlyArray<{ title: string; body: string; labels: string[] }>;
}

export async function exportSuggestionsToGithub(
  suggestions: ReadonlyArray<ExportableSuggestion>,
  options: GithubExportOptions,
): Promise<GithubExportResult> {
  if (suggestions.length === 0) {
    return { batchId: null, draftIds: [], dryRun: !!options.dryRun, previews: [] };
  }

  const previews = suggestions.map((s) => ({
    title: s.title,
    body: renderTestCaseBody(s),
    labels: dedupe(["type:test", ...(s.tags ?? []), ...(options.additionalLabels ?? [])]),
  }));

  if (options.dryRun) {
    return { batchId: null, draftIds: [], dryRun: true, previews };
  }

  const draftIds: string[] = [];
  for (let i = 0; i < suggestions.length; i += 1) {
    const s = suggestions[i];
    const preview = previews[i];
    const draft = await prisma.issueDraft.create({
      data: {
        projectId: options.projectId,
        requirementId: s.mappedRequirementIds[0] ?? null,
        parentDraftId: null,
        draftType: "task",
        title: preview.title,
        body: preview.body,
        labels: JSON.stringify(preview.labels),
        assignees: JSON.stringify([]),
        storyPoints: storyPointsFor(s),
        status: "draft",
        dedupHash: s.id, // suggestion id is already a stable dedup key
        metadata: JSON.stringify({
          source: "test-coverage-export",
          suggestionId: s.id,
          mappedRequirementIds: s.mappedRequirementIds,
          faithfulness: s.faithfulness,
          lowConfidence: s.lowConfidence,
        }),
      },
      select: { id: true },
    });
    draftIds.push(draft.id);
  }

  const batchInput: CreatePublishBatchInput = {
    projectId: options.projectId,
    targetOwner: options.targetOwner,
    targetRepo: options.targetRepo,
    provider: "github",
    draftIds,
    dryRun: false,
    additionalLabels: [...(options.additionalLabels ?? [])],
    ...(options.milestone !== undefined ? { milestone: options.milestone } : {}),
    ...(options.secretRef ? { secretRef: options.secretRef } : {}),
    metadata: { exporter: "test-coverage" },
  };
  const batch = await createBatch({
    input: batchInput,
    actorId: options.actorId,
    confirmCrossProject: options.confirmCrossProject,
  });
  await executeBatch({ batchId: batch.id, actorId: options.actorId });
  return { batchId: batch.id, draftIds, dryRun: false, previews };
}

export function renderTestCaseBody(s: ExportableSuggestion): string {
  const stepsBlock = s.steps
    .map((step, idx) => `${idx + 1}. ${step.action}${step.expected ? ` → ${step.expected}` : ""}`)
    .join("\n");

  const reqList = s.mappedRequirementIds.length
    ? s.mappedRequirementIds.map((id) => `- ${id}`).join("\n")
    : "_(none)_";

  return [
    `<!-- generated by metis test-coverage exporter -->`,
    ``,
    `## Acceptance Criteria (Given / When / Then)`,
    ``,
    `**Given**`,
    ``,
    formatBlock(s.gwt.given),
    ``,
    `**When**`,
    ``,
    formatBlock(s.gwt.when),
    ``,
    `**Then**`,
    ``,
    formatBlock(s.gwt.then),
    ``,
    `## Preconditions`,
    ``,
    s.preconditions?.trim() || "_(none)_",
    ``,
    `## Steps`,
    ``,
    stepsBlock || "_(none)_",
    ``,
    `## Expected Result`,
    ``,
    s.expected?.trim() || formatBlock(s.gwt.then) || "_(none)_",
    ``,
    `## Mapped Requirements`,
    ``,
    reqList,
    ``,
    `## Metadata`,
    ``,
    `- Suggestion ID: \`${s.id}\``,
    `- Faithfulness: ${s.faithfulness.toFixed(2)}`,
    `- Low confidence: ${s.lowConfidence ? "**yes**" : "no"}`,
    `- Priority: ${s.priority ?? "(unspecified)"}`,
  ].join("\n");
}

function formatBlock(text: string | ReadonlyArray<string> | undefined): string {
  if (!text) return "";
  const list = Array.isArray(text) ? text : [text as string];
  return list
    .flatMap((s) => s.split(/\r?\n/))
    .map((s) => s.trim())
    .filter(Boolean)
    .map((line) => `- ${line}`)
    .join("\n");
}

function storyPointsFor(s: ExportableSuggestion): number {
  if (s.priority === "critical") return 5;
  if (s.priority === "high") return 3;
  if (s.priority === "low") return 1;
  return 2;
}

function dedupe(values: ReadonlyArray<string>): string[] {
  return [...new Set(values.filter((v) => v && v.length > 0))];
}
