/**
 * Epic #396 (MVP-7) — per-host prompt emitters.
 *
 * Each host scans a different prompt directory:
 *   - copilot → `.github/prompts/speckit.<cmd>.prompt.md`
 *   - claude  → `.claude/commands/speckit.<cmd>.md`
 *   - cursor  → `.cursor/commands/speckit.<cmd>.md`
 *   - pi      → `.pi/prompts/speckit.<cmd>.md`
 *
 * The prompt body is METIS-flavored: it instructs the host's LLM to call
 * the METIS REST surface `POST /api/projects/<projectId>/spec-kit/command`
 * — the host sees a standard `/speckit.*` command and never knows METIS
 * is the backend.
 */
import { SPECKIT_COMMANDS } from "@metis/shared";
// Re-exported from `lib/net/api-base-url.ts` so existing import sites
// (`from "./hosts.js"`) keep compiling. Issue #438 — extracted to a shared
// module so non-installer callers (MCP dispatcher, future webhook senders)
// don't reach across the installer boundary.
export { assertApiBaseUrlAllowed } from "../../net/api-base-url.js";

export type HostKey = "copilot" | "claude" | "cursor" | "pi" | "codex";

export const HOSTS: readonly HostKey[] = ["copilot", "claude", "cursor", "pi", "codex"];

export function isHostKey(s: string): s is HostKey {
  return (HOSTS as readonly string[]).includes(s);
}

export interface HostFile {
  /** Path relative to the workspace root. */
  relPath: string;
  content: string;
}

export interface HostEmitContext {
  projectId: string;
  /** Absolute base URL for the METIS API (e.g. `https://metis.local`). */
  apiBaseUrl: string;
}

/**
 * Build the prompt body for a single command. Same body for every host —
 * only the file path / extension differ.
 */
export function buildPromptBody(cmd: string, ctx: HostEmitContext): string {
  return [
    `# /${cmd}`,
    "",
    "<!-- Generated by METIS Spec Kit installer (Epic #396). Do not edit by hand. -->",
    "",
    `When the user invokes \`/${cmd}\` in this workspace, POST the user's input to`,
    `the METIS Spec Kit REST surface and return the resulting artifact verbatim.`,
    "",
    "## Request",
    "",
    "```",
    `POST ${ctx.apiBaseUrl}/api/projects/${ctx.projectId}/spec-kit/commands/${cmd}`,
    "Content-Type: application/json",
    "Authorization: Bearer ${METIS_TOKEN}",
    "",
    `{ "input": "<everything after /${cmd}>" }`,
    "```",
    "",
    "## Response handling",
    "",
    "- HTTP 200 → render `data.message` to the user, then attach `data.artifact.content` as the canonical artifact.",
    "- HTTP 412 → relay the structured error body (a phase prerequisite is unmet — surface the `required` gate).",
    "- HTTP 422 → relay the safety-block reason verbatim.",
    "",
    "Never invent the artifact content yourself — METIS owns the agent chain.",
    "",
  ].join("\n");
}

const HOST_DIR: Record<HostKey, string> = {
  copilot: ".github/prompts",
  claude: ".claude/commands",
  cursor: ".cursor/commands",
  pi: ".pi/prompts",
  codex: ".codex/skills/speckit",
};

const HOST_EXT: Record<HostKey, string> = {
  copilot: ".prompt.md",
  claude: ".md",
  cursor: ".md",
  pi: ".md",
  codex: ".md",
};

/**
 * Issue #432 — canonical mapping of `speckit.*` namespaced commands to
 * Codex's `$speckit-*` skill aliases (dollar prefix, dash separator).
 */
export const CODEX_ALIAS_MAP: Readonly<Record<string, string>> = Object.fromEntries(
  SPECKIT_COMMANDS.map((cmd) => [cmd, `$${cmd.replace(/\./g, "-")}`]),
);

/**
 * Issue #432 — convert a Codex `$speckit-foo` alias back to the canonical
 * `speckit.foo` form. Returns null when the alias is not recognised.
 */
export function resolveCodexAlias(alias: string): string | null {
  for (const [canonical, codex] of Object.entries(CODEX_ALIAS_MAP)) {
    if (codex === alias) return canonical;
  }
  return null;
}

export function emitHostFiles(host: HostKey, ctx: HostEmitContext): HostFile[] {
  const dir = HOST_DIR[host];
  const ext = HOST_EXT[host];
  // Codex skill filenames use the `$speckit-foo` alias form (without the
  // dollar prefix, which is illegal in many filesystems).
  const renderName = (cmd: string): string =>
    host === "codex" ? `speckit-${cmd.replace(/^speckit\./, "")}` : cmd;
  return SPECKIT_COMMANDS.map((cmd) => ({
    relPath: `${dir}/${renderName(cmd)}${ext}`,
    content: buildPromptBody(cmd, ctx),
  }));
}

// ---------------------------------------------------------------------------
// Issue #432 — AGENTS.md emission for Codex (and any future host that uses
// the upstream OpenAI Codex CLI's per-workspace skills convention).
// ---------------------------------------------------------------------------

export const AGENTS_MD_BEGIN = "<!-- speckit:start -->";
export const AGENTS_MD_END = "<!-- speckit:end -->";

/**
 * Build the `## Spec Kit Skills` section that lives between the marker
 * comments inside `AGENTS.md`. The section enumerates every `$speckit-*`
 * alias and maps it to the underlying canonical command + REST endpoint.
 */
export function buildAgentsMdSection(ctx: HostEmitContext): string {
  const lines = [
    AGENTS_MD_BEGIN,
    "## Spec Kit Skills",
    "",
    "<!-- Generated by METIS Spec Kit installer (Issue #432). Do not edit by hand. -->",
    "",
    "When the user invokes any of the dollar-prefixed skills below, dispatch the user's input to METIS via the documented endpoint. METIS owns the agent chain — relay responses verbatim.",
    "",
    "| Codex skill | Canonical command | Endpoint |",
    "|---|---|---|",
  ];
  for (const cmd of SPECKIT_COMMANDS) {
    const alias = CODEX_ALIAS_MAP[cmd];
    lines.push(
      `| \`${alias}\` | \`/${cmd}\` | \`POST ${ctx.apiBaseUrl}/api/projects/${ctx.projectId}/spec-kit/commands/${cmd}\` |`,
    );
  }
  lines.push(
    "",
    "All skills require `Authorization: Bearer ${METIS_TOKEN}`. See `.codex/skills/speckit/` for the full prompt body of each skill.",
    "",
    AGENTS_MD_END,
    "",
  );
  return lines.join("\n");
}

/**
 * Merge the generated section into an existing `AGENTS.md` body. If the
 * marker comments are present, the block between them is replaced; the
 * surrounding content is preserved exactly. If the markers are absent,
 * the new section is appended after a blank line. Empty/whitespace input
 * produces a fresh document containing only the section.
 */
export function mergeAgentsMd(existing: string, ctx: HostEmitContext): string {
  const section = buildAgentsMdSection(ctx);
  const trimmed = existing?.trimEnd() ?? "";
  if (trimmed.length === 0) return section;
  const startIdx = existing.indexOf(AGENTS_MD_BEGIN);
  const endIdx = existing.indexOf(AGENTS_MD_END);
  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    const before = existing.slice(0, startIdx);
    const after = existing.slice(endIdx + AGENTS_MD_END.length);
    // Drop a single trailing newline from `after` if present so we do not
    // accumulate blank lines on every re-run.
    const cleanedAfter = after.replace(/^\n/, "");
    return `${before}${section}${cleanedAfter}`;
  }
  // Append — preserve the existing content + a single blank line.
  return `${trimmed}\n\n${section}`;
}

/**
 * Convenience: produce the `AGENTS.md` HostFile alongside the per-skill
 * files for the Codex host.
 */
export function emitCodexAgentsMd(ctx: HostEmitContext, existing = ""): HostFile {
  return { relPath: "AGENTS.md", content: mergeAgentsMd(existing, ctx) };
}
