/**
 * .copilot-workspace.md handoff brief renderer — Epic #163, Issue #97.
 *
 * Format follows the Copilot Workspace `workspace.md` spec:
 * https://github.com/microsoft/copilot-workspace#workspacemd
 *
 *   # Workspace
 *   ## <epic title>
 *   - Number, title, story points, dependencies for each sub-issue.
 *
 * The renderer is pure — no I/O, no Prisma, no octokit. The publisher wires
 * its output into a single GitHub `PUT /repos/{o}/{r}/contents/.copilot-workspace.md`
 * commit when `metadata.copilotWorkspace === true`.
 */

export interface WorkspaceSubIssue {
  number: number;
  title: string;
  storyPoints?: number | null;
  /** Issue numbers this sub-issue depends on (publish order seed). */
  dependencies?: number[];
}

export interface WorkspaceEpic {
  number: number;
  title: string;
  /** First-paragraph summary; rendered under the section heading. */
  summary?: string;
  subIssues: WorkspaceSubIssue[];
}

export interface RenderWorkspaceInput {
  /** All epics published in this batch. Sorted as caller passes them. */
  epics: WorkspaceEpic[];
  /** Optional generator timestamp (ISO 8601). Defaults to now. Used in tests. */
  generatedAt?: string;
  /** Repo `owner/repo` for the human-readable footer. */
  repo?: string;
}

export const COPILOT_WORKSPACE_PATH = ".copilot-workspace.md";

/**
 * Render the workspace markdown. Stable output — re-running with identical
 * input produces byte-identical bytes (so the publisher's idempotency check
 * never produces a no-op commit).
 */
export function renderCopilotWorkspaceMarkdown(input: RenderWorkspaceInput): string {
  const lines: string[] = [];
  lines.push("# Workspace");
  lines.push("");
  lines.push(
    "_Generated by METIS — see <https://github.com/microsoft/copilot-workspace#workspacemd>._",
  );
  if (input.repo) lines.push("", `Repo: \`${input.repo}\``);
  lines.push("");

  if (input.epics.length === 0) {
    lines.push("> No epics in this batch.");
    lines.push("");
    return lines.join("\n");
  }

  for (const epic of input.epics) {
    lines.push(`## #${epic.number} — ${epic.title}`);
    lines.push("");
    if (epic.summary) {
      lines.push(epic.summary.trim());
      lines.push("");
    }
    lines.push("### Sub-issues");
    lines.push("");
    if (epic.subIssues.length === 0) {
      lines.push("_No sub-issues._");
      lines.push("");
      continue;
    }
    lines.push("| # | Title | Story Points | Dependencies |");
    lines.push("|---|-------|--------------|--------------|");
    for (const sub of epic.subIssues) {
      const sp =
        typeof sub.storyPoints === "number" && Number.isFinite(sub.storyPoints)
          ? String(sub.storyPoints)
          : "—";
      const deps =
        sub.dependencies && sub.dependencies.length > 0
          ? sub.dependencies.map((n) => `#${n}`).join(", ")
          : "—";
      const safeTitle = escapeTableCell(sub.title);
      lines.push(`| #${sub.number} | ${safeTitle} | ${sp} | ${deps} |`);
    }
    lines.push("");
  }

  if (input.generatedAt) {
    lines.push(`<!-- generated: ${input.generatedAt} -->`);
  }

  return lines.join("\n");
}

/**
 * Compute a stable SHA-256 hex digest of the rendered markdown so the
 * publisher can decide whether to PUT a new commit (content changed) or
 * skip (identical bytes).
 */
export async function workspaceContentHash(content: string): Promise<string> {
  const { createHash } = await import("node:crypto");
  return createHash("sha256").update(content, "utf-8").digest("hex");
}

function escapeTableCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ").trim();
}
