/**
 * Idempotent label sync — Phase 9 (#67).
 *
 * Uses `PUT /repos/{owner}/{repo}/labels/{name}` so existing labels are
 * upserted in place (color/description updated) and new labels are created
 * on first encounter. The plain `POST /labels` endpoint would 422 on
 * duplicates and break a publish run.
 *
 * Labels are deduplicated by name (case-insensitive) before being sent.
 */
import type { PublishOctokitLike, GhLabel } from "./types.js";

export const DEFAULT_PUBLISH_LABELS: GhLabel[] = [
  { name: "epic", color: "3E4B9E", description: "Top-level epic grouping" },
  { name: "feature", color: "0E8A16", description: "New feature or functionality" },
  { name: "bug", color: "d73a4a", description: "Something isn't working" },
  { name: "task", color: "a2eeef", description: "Development task" },
  { name: "metis-generated", color: "7057ff", description: "Generated by METIS" },
  { name: "priority:critical", color: "b60205", description: "Critical priority" },
  { name: "priority:high", color: "e11d48", description: "High priority" },
  { name: "priority:medium", color: "fbca04", description: "Medium priority" },
  { name: "priority:low", color: "c5def5", description: "Low priority" },
];

export interface SyncLabelsResult {
  upserted: number;
  failed: number;
  errors: Array<{ name: string; message: string }>;
}

export async function syncLabels(
  client: PublishOctokitLike,
  target: { owner: string; repo: string },
  labels: GhLabel[],
): Promise<SyncLabelsResult> {
  const seen = new Set<string>();
  const result: SyncLabelsResult = { upserted: 0, failed: 0, errors: [] };
  for (const label of labels) {
    const key = label.name.trim().toLowerCase();
    if (!key || seen.has(key)) continue;
    seen.add(key);
    try {
      await client.request({
        method: "PUT",
        url: `/repos/${encodeURIComponent(target.owner)}/${encodeURIComponent(target.repo)}/labels/${encodeURIComponent(label.name)}`,
        data: {
          new_name: label.name,
          color: label.color,
          description: label.description ?? "",
        },
      });
      result.upserted += 1;
    } catch (err) {
      const e = err as { status?: number; message?: string };
      // 404 = label does not exist yet — fall back to POST /labels.
      if (e.status === 404) {
        try {
          await client.request({
            method: "POST",
            url: `/repos/${encodeURIComponent(target.owner)}/${encodeURIComponent(target.repo)}/labels`,
            data: {
              name: label.name,
              color: label.color,
              description: label.description ?? "",
            },
          });
          result.upserted += 1;
          continue;
        } catch (createErr) {
          const ce = createErr as { message?: string };
          result.failed += 1;
          result.errors.push({ name: label.name, message: ce.message ?? "create failed" });
          continue;
        }
      }
      result.failed += 1;
      result.errors.push({ name: label.name, message: e.message ?? "label upsert failed" });
    }
  }
  return result;
}

/** Combine a base label list with the user-supplied additional labels. */
export function combineLabels(base: GhLabel[], extras: string[]): GhLabel[] {
  const out: GhLabel[] = [...base];
  const known = new Set(out.map((l) => l.name.toLowerCase()));
  for (const name of extras) {
    const trimmed = name.trim();
    if (!trimmed || known.has(trimmed.toLowerCase())) continue;
    known.add(trimmed.toLowerCase());
    out.push({ name: trimmed, color: "ededed", description: "Custom label from METIS" });
  }
  return out;
}
