/**
 * #334 — Judge-gated escalation (quality floor).
 *
 * When a section is generated on the LOCAL provider and its faithfulness score
 * falls below that section's tier threshold, the section is re-run ONCE on the
 * escalation (Sonnet/cloud) provider and the better result is kept. Escalation
 * is flag-gated (`DOCS_GEN_JUDGE_ESCALATION`, default OFF), bounded by a
 * per-document budget (`DOCS_GEN_MAX_ESCALATIONS`), observable (logged +
 * counted), and records cloud token usage.
 *
 * This suite splits into two layers:
 *   1. `shouldEscalateSection` — the PURE gate. The full decision matrix is
 *      exercised here (flag off, no hybrid, cloud section, above-threshold,
 *      unverified, budget exhausted, and the one true-escalate case).
 *   2. `synthesizeFinalDocument` — the INTEGRATION. Fake providers emit
 *      distinguishable markdown per provider; `scoreFaithfulness` is mocked to
 *      drive deterministic local/escalated scores. We assert: below-threshold
 *      local → escalates + keeps escalated when higher; above-threshold →
 *      no escalation; escalated-still-below → keeps better + warns; flag OFF →
 *      no escalation (byte-identical single-provider behavior); at-most-one
 *      re-run per section (no loop); budget cap; escalation event logged;
 *      cloud usage recorded.
 *
 * No live model serving / LLM calls — providers are fakes and the scorer is
 * mocked (mirrors the #333 hybrid-routing test's live-dependency discipline).
 */
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

// The faithfulness scorer is mocked so we can drive exact scores per output
// WITHOUT running a real claim extractor / NLI judge. Hoisted per Vitest rules.
const scoreFaithfulnessMock = vi.hoisted(() => vi.fn());
const recordUsageMock = vi.hoisted(() => vi.fn());

vi.mock("./grounding/citation-validator.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("./grounding/citation-validator.js")>();
  return { ...actual, scoreFaithfulness: scoreFaithfulnessMock };
});

vi.mock("../finops/index.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../finops/index.js")>();
  return { ...actual, recordUsage: recordUsageMock };
});

import type { AIProvider, ChatChunk, ChatMessage, ChatOptions, ProviderKey } from "../ai/types.js";
import type { GroundingContext } from "./grounding/grounding-context.js";
import type { FaithfulnessResult } from "./grounding/citation-validator.js";
import {
  shouldEscalateSection,
  resolveEscalationConfig,
  DEFAULT_MAX_ESCALATIONS,
  docsGenTuning,
  synthesizeFinalDocument,
  sectionGroupsFor,
  type Phase2ProviderBundle,
  type Phase2Router,
  type ModuleFacts,
} from "./holistic-synthesizer.js";

// ── Test doubles ─────────────────────────────────────────────────────────

/**
 * A fake AIProvider whose `stream()` yields one deterministic markdown section
 * (tagged with `marker` so the mocked scorer can tell local vs escalated apart)
 * plus a usage chunk. Records how many times it streamed.
 */
function fakeProvider(key: ProviderKey, marker: string): AIProvider & { streamCalls: number } {
  const p = {
    key,
    model: `${key}-model`,
    offline: false,
    streamCalls: 0,
    async *stream(_messages: ChatMessage[], _opts?: ChatOptions): AsyncGenerator<ChatChunk> {
      p.streamCalls += 1;
      // Unique H2 per call so `dedupeH2Sections` never collapses distinct
      // sections (real section groups all have distinct headings).
      yield {
        type: "delta",
        content: `## ${marker} Section ${p.streamCalls}\n\nBody generated by ${marker}.`,
      };
      yield {
        type: "usage",
        usage: { promptTokens: 100, completionTokens: 200, cacheReadTokens: 0 },
      };
    },
    async chat(): Promise<never> {
      throw new Error("chat not used in these tests");
    },
    async embed(): Promise<never> {
      throw new Error("embed not used");
    },
    async models(): Promise<string[]> {
      return [];
    },
    async ping(): Promise<boolean> {
      return true;
    },
  };
  return p as AIProvider & { streamCalls: number };
}

function bundle(kind: Phase2ProviderBundle["kind"], provider: AIProvider): Phase2ProviderBundle {
  const tuning = docsGenTuning(kind === "local" ? "local" : "anthropic", provider.model);
  return {
    kind,
    provider,
    supportsCaching: false,
    factsCharCap: tuning.factsCharCap,
    tuning,
  };
}

const LOCAL_MARKER = "LOCAL-PROVIDER";
const ESC_MARKER = "ESCALATION-PROVIDER";

function makeHybridRouter(): {
  router: Phase2Router;
  local: AIProvider & { streamCalls: number };
  escalation: AIProvider & { streamCalls: number };
} {
  const local = fakeProvider("local-gemma", LOCAL_MARKER);
  const escalation = fakeProvider("anthropic", ESC_MARKER);
  const localBundle = bundle("local", local);
  const escBundle = bundle("anthropic", escalation);
  const primary = localBundle;
  return {
    router: { primary, hybrid: { local: localBundle, escalation: escBundle } },
    local,
    escalation,
  };
}

/** A non-empty grounding context (escalation only fires when grounding is active). */
function groundingCtx(): GroundingContext {
  return {
    sources: [{ id: "facts:mod:0", text: "evidence", kind: "facts" } as never],
    sourceIds: new Set(["facts:mod:0"]),
    isEmpty: false,
  };
}

function fakeFacts(): ModuleFacts[] {
  return [
    {
      modulePath: "src/mod",
      moduleName: "mod",
      classCount: 1,
      methodCount: 2,
      facts: "The module validates orders and computes totals.",
      formulas: [],
      topClasses: ["OrderService"],
    },
  ];
}

const META = {
  name: "Test Project",
  totalFiles: 3,
  totalSymbols: 42,
  languages: ["typescript"],
} as never;

/** Build a FaithfulnessResult with the given ratio and a couple of claims. */
function result(faithfulness: number): FaithfulnessResult {
  return {
    section: "Section",
    totalClaims: 10,
    supportedClaims: Math.round(faithfulness * 10),
    faithfulness,
    verified: true,
    unsupportedClaims: [],
    supportedAttributions: [],
  };
}

const ENV_KEYS = ["DOCS_GEN_JUDGE_ESCALATION", "DOCS_GEN_MAX_ESCALATIONS"] as const;
const saved: Record<string, string | undefined> = {};

beforeEach(() => {
  for (const k of ENV_KEYS) {
    saved[k] = process.env[k];
    delete process.env[k];
  }
  scoreFaithfulnessMock.mockReset();
  recordUsageMock.mockReset();
});

afterEach(() => {
  for (const k of ENV_KEYS) {
    if (saved[k] === undefined) delete process.env[k];
    else process.env[k] = saved[k];
  }
});

// ── 1. The pure gate ───────────────────────────────────────────────────────

describe("shouldEscalateSection — the decision gate", () => {
  const { router } = makeHybridRouter();
  const localBundle = router.hybrid!.local;
  const escBundle = router.hybrid!.escalation;
  const on = { enabled: true, maxEscalations: 3 };
  const below = { faithfulness: 0.5, threshold: 0.8 };

  it("escalates a below-threshold LOCAL section when everything aligns", () => {
    expect(
      shouldEscalateSection({
        config: on,
        router,
        sectionBundle: localBundle,
        score: below,
        escalationsUsed: 0,
      }),
    ).toBe(true);
  });

  it("does NOT escalate when the flag is OFF", () => {
    expect(
      shouldEscalateSection({
        config: { enabled: false, maxEscalations: 3 },
        router,
        sectionBundle: localBundle,
        score: below,
        escalationsUsed: 0,
      }),
    ).toBe(false);
  });

  it("does NOT escalate when hybrid routing is inactive (no escalation target)", () => {
    expect(
      shouldEscalateSection({
        config: on,
        router: { primary: localBundle, hybrid: null },
        sectionBundle: localBundle,
        score: below,
        escalationsUsed: 0,
      }),
    ).toBe(false);
  });

  it("does NOT escalate a section that already ran on the CLOUD provider", () => {
    expect(
      shouldEscalateSection({
        config: on,
        router,
        sectionBundle: escBundle,
        score: below,
        escalationsUsed: 0,
      }),
    ).toBe(false);
  });

  it("does NOT escalate an at-or-above-threshold section", () => {
    expect(
      shouldEscalateSection({
        config: on,
        router,
        sectionBundle: localBundle,
        score: { faithfulness: 0.85, threshold: 0.8 },
        escalationsUsed: 0,
      }),
    ).toBe(false);
  });

  it("does NOT escalate an UNVERIFIED section (null score)", () => {
    expect(
      shouldEscalateSection({
        config: on,
        router,
        sectionBundle: localBundle,
        score: null,
        escalationsUsed: 0,
      }),
    ).toBe(false);
  });

  it("does NOT escalate once the per-document budget is exhausted", () => {
    expect(
      shouldEscalateSection({
        config: { enabled: true, maxEscalations: 2 },
        router,
        sectionBundle: localBundle,
        score: below,
        escalationsUsed: 2,
      }),
    ).toBe(false);
  });
});

describe("resolveEscalationConfig", () => {
  it("defaults to OFF with the default budget", () => {
    const cfg = resolveEscalationConfig();
    expect(cfg.enabled).toBe(false);
    expect(cfg.maxEscalations).toBe(DEFAULT_MAX_ESCALATIONS);
  });

  it("reads the flag and budget from env", () => {
    process.env.DOCS_GEN_JUDGE_ESCALATION = "1";
    process.env.DOCS_GEN_MAX_ESCALATIONS = "7";
    const cfg = resolveEscalationConfig();
    expect(cfg.enabled).toBe(true);
    expect(cfg.maxEscalations).toBe(7);
  });

  it("allows a budget of 0 (flag on but escalation disabled by budget)", () => {
    process.env.DOCS_GEN_MAX_ESCALATIONS = "0";
    expect(resolveEscalationConfig().maxEscalations).toBe(0);
  });
});

// ── 2. Integration through the per-section loop ──────────────────────────────

/**
 * Drive `scoreFaithfulness` by which marker the scored markdown contains, so
 * the local output and the escalated re-run get INDEPENDENT scores.
 */
function scoreByMarker(scores: { local: number; escalation: number }): void {
  scoreFaithfulnessMock.mockImplementation(
    async (_section: string, markdown: string): Promise<FaithfulnessResult> => {
      if (markdown.includes(ESC_MARKER)) return result(scores.escalation);
      if (markdown.includes(LOCAL_MARKER)) return result(scores.local);
      return result(1);
    },
  );
}

async function run(router: Phase2Router) {
  return synthesizeFinalDocument(
    fakeFacts(),
    META,
    "business-requirements",
    "Test Doc",
    router,
    "proj-1",
    groundingCtx(),
  );
}

// Under #333 hybrid routing, narrative sections route to the escalation provider
// as their PRIMARY (not as a #334 re-run). So the escalation provider's baseline
// stream count is the narrative-section count; #334 re-runs are ON TOP of that.
const BR_GROUPS = sectionGroupsFor("business-requirements");
const NARRATIVE_COUNT = BR_GROUPS.filter((g) => g.narrative).length;
const LOCAL_TIER_COUNT = BR_GROUPS.filter((g) => !g.narrative).length;

describe("synthesizeFinalDocument — judge-gated escalation integration", () => {
  it("escalates a below-threshold LOCAL section and keeps the higher-scoring cloud output", async () => {
    process.env.DOCS_GEN_JUDGE_ESCALATION = "1";
    process.env.DOCS_GEN_MAX_ESCALATIONS = "50";
    // Local literal sections fail (0.5 < 0.8); the escalated re-run passes (0.95).
    scoreByMarker({ local: 0.5, escalation: 0.95 });
    const { router, escalation } = makeHybridRouter();

    const { markdown, warnings } = await run(router);

    // The escalation provider actually ran, and its content is in the document.
    expect(escalation.streamCalls).toBeGreaterThan(0);
    expect(markdown).toContain(ESC_MARKER);
    // The kept (escalated) sections passed → no faithfulness warning for them.
    expect(warnings.filter((w) => w.kind === "section-ungrounded")).toHaveLength(0);
  });

  it("does NOT escalate a section already above threshold", async () => {
    process.env.DOCS_GEN_JUDGE_ESCALATION = "1";
    // Every local section passes.
    scoreByMarker({ local: 0.95, escalation: 0.95 });
    const { router, escalation } = makeHybridRouter();

    const { markdown } = await run(router);

    // Only the narrative-section PRIMARIES hit the escalation provider (#333),
    // never a #334 re-run.
    expect(escalation.streamCalls).toBe(NARRATIVE_COUNT);
    expect(markdown).toContain(LOCAL_MARKER);
  });

  it("keeps the BETTER output and still WARNS when the escalated re-run is also below threshold", async () => {
    process.env.DOCS_GEN_JUDGE_ESCALATION = "1";
    // Local 0.3 → escalate; escalated 0.6 still below the 0.8 literal bar but higher.
    scoreByMarker({ local: 0.3, escalation: 0.6 });
    const { router, escalation } = makeHybridRouter();

    const { markdown, warnings } = await run(router);

    expect(escalation.streamCalls).toBeGreaterThan(0);
    // Higher-scoring escalated output kept…
    expect(markdown).toContain(ESC_MARKER);
    // …but it is still below the bar, so a warning is surfaced (never a false ready).
    expect(warnings.filter((w) => w.kind === "section-ungrounded").length).toBeGreaterThan(0);
  });

  it("keeps the LOCAL output when the escalated re-run scores LOWER", async () => {
    process.env.DOCS_GEN_JUDGE_ESCALATION = "1";
    process.env.DOCS_GEN_MAX_ESCALATIONS = "50";
    // Local 0.55 < 0.8 → escalate; escalated 0.4 is WORSE → keep local.
    scoreByMarker({ local: 0.55, escalation: 0.4 });
    const { router, escalation } = makeHybridRouter();

    const { markdown } = await run(router);

    // It DID try to escalate (baseline narrative primaries + one re-run per local
    // section), but the better local output won for every local section.
    expect(escalation.streamCalls).toBe(NARRATIVE_COUNT + LOCAL_TIER_COUNT);
    expect(markdown).toContain(LOCAL_MARKER); // the better local output won
  });

  it("does NOT escalate when the flag is OFF (unchanged single-hybrid behavior)", async () => {
    // Flag intentionally unset. Local sections fail, but escalation is inert.
    scoreByMarker({ local: 0.2, escalation: 0.99 });
    const { router, escalation } = makeHybridRouter();

    const { warnings } = await run(router);

    // No #334 re-runs: the escalation provider only served narrative primaries.
    expect(escalation.streamCalls).toBe(NARRATIVE_COUNT);
    // The below-threshold local sections still warn (routing/gating unchanged).
    expect(warnings.filter((w) => w.kind === "section-ungrounded").length).toBeGreaterThan(0);
  });

  it("escalates at most ONCE per section (no loop even when the re-run is still below)", async () => {
    process.env.DOCS_GEN_JUDGE_ESCALATION = "1";
    // Budget high enough that it does NOT mask the no-loop property.
    process.env.DOCS_GEN_MAX_ESCALATIONS = "50";
    // Both local and escalated are below the bar → the re-run must NOT re-trigger.
    scoreByMarker({ local: 0.2, escalation: 0.3 });
    const { router, escalation } = makeHybridRouter();

    await run(router);

    // Exactly one escalation re-run per escalatable local section (never more),
    // on top of the narrative primaries — proving no loop.
    expect(escalation.streamCalls).toBe(NARRATIVE_COUNT + LOCAL_TIER_COUNT);
  });

  it("respects the per-document escalation budget cap", async () => {
    process.env.DOCS_GEN_JUDGE_ESCALATION = "1";
    process.env.DOCS_GEN_MAX_ESCALATIONS = "1";
    scoreByMarker({ local: 0.2, escalation: 0.95 });
    const { router, escalation } = makeHybridRouter();

    await run(router);

    // Budget of 1 → only ONE below-threshold local section escalates (on top of
    // the narrative primaries).
    expect(escalation.streamCalls).toBe(NARRATIVE_COUNT + 1);
  });

  it("records CLOUD token usage for the escalated re-run", async () => {
    process.env.DOCS_GEN_JUDGE_ESCALATION = "1";
    process.env.DOCS_GEN_MAX_ESCALATIONS = "1";
    scoreByMarker({ local: 0.2, escalation: 0.95 });
    const { router } = makeHybridRouter();

    await run(router);

    // At least one usage record was attributed to the escalation (anthropic) provider.
    const cloudUsage = recordUsageMock.mock.calls.filter((c) => c[0]?.provider === "anthropic");
    expect(cloudUsage.length).toBeGreaterThan(0);
    expect(cloudUsage[0][0]).toMatchObject({ projectId: "proj-1", provider: "anthropic" });
  });

  it("keeps the local section (with its warning) when the escalation re-run THROWS", async () => {
    process.env.DOCS_GEN_JUDGE_ESCALATION = "1";
    process.env.DOCS_GEN_MAX_ESCALATIONS = "50";
    scoreByMarker({ local: 0.3, escalation: 0.95 });
    // Escalation provider that fails mid-stream: synthesis must NOT crash and the
    // local output (with its below-threshold warning) must be kept.
    const local = fakeProvider("local-gemma", LOCAL_MARKER);
    const escalation: AIProvider = {
      key: "anthropic",
      model: "anthropic-model",
      offline: false,
      async *stream(): AsyncGenerator<ChatChunk> {
        throw new Error("escalation provider unavailable");
        yield { type: "delta", content: "" }; // unreachable — satisfies generator typing
      },
      async chat(): Promise<never> {
        throw new Error("chat not used");
      },
      async embed(): Promise<never> {
        throw new Error("embed not used");
      },
      async models(): Promise<string[]> {
        return [];
      },
      async ping(): Promise<boolean> {
        return true;
      },
    };
    const localBundle = bundle("local", local);
    const escBundle = bundle("anthropic", escalation);
    const router: Phase2Router = {
      primary: localBundle,
      hybrid: { local: localBundle, escalation: escBundle },
    };

    // Narrative sections ALSO route to the (throwing) escalation provider as their
    // #333 primary; those become `section-failed`. The point of this test is that
    // synthesis SURVIVES and the escalatable local sections keep their local
    // output + faithfulness warning rather than crashing.
    const { markdown, warnings } = await run(router);
    expect(markdown).toContain(LOCAL_MARKER);
    expect(warnings.filter((w) => w.kind === "section-ungrounded").length).toBeGreaterThan(0);
  });

  it("is a no-op when hybrid routing is inactive even with the flag ON", async () => {
    process.env.DOCS_GEN_JUDGE_ESCALATION = "1";
    scoreByMarker({ local: 0.2, escalation: 0.95 });
    // Single-provider router: primary only, no hybrid pair.
    const local = fakeProvider("local-gemma", LOCAL_MARKER);
    const router: Phase2Router = { primary: bundle("local", local), hybrid: null };

    const { markdown, warnings } = await run(router);

    expect(markdown).not.toContain(ESC_MARKER);
    expect(warnings.filter((w) => w.kind === "section-ungrounded").length).toBeGreaterThan(0);
  });
});
