/**
 * #945 — the Spec Kit page's display helpers.
 */
import { afterEach, describe, expect, it } from "vitest";
import { ApiError } from "@/lib/api-client";
import {
  describeSpecKitError,
  displayArtifactText,
  isMarkdownArtifact,
  isNoProjectAccess,
  loadHandoff,
  saveHandoff,
} from "@/lib/spec-kit-display";

describe("displayArtifactText", () => {
  it("drops the checklist's base64 marker line and keeps everything else", () => {
    const md = [
      "# Security checklist",
      "<!-- Generated by /speckit.checklist -->",
      "  <!-- speckit-generated-checks: WyJhIl0= -->",
      "- [ ] CSRF on the new POST",
    ].join("\n");
    expect(displayArtifactText(md)).toBe(
      "# Security checklist\n<!-- Generated by /speckit.checklist -->\n- [ ] CSRF on the new POST",
    );
  });
});

describe("isMarkdownArtifact", () => {
  it("renders .md and leaves the YAML contract as text", () => {
    expect(isMarkdownArtifact("checklists/security.md")).toBe(true);
    expect(isMarkdownArtifact("PLAN.MD")).toBe(true);
    expect(isMarkdownArtifact("contracts/api.openapi.yaml")).toBe(false);
  });
});

describe("describeSpecKitError", () => {
  it("names the missing artifact for an unmet gate, without API field names", () => {
    const err = new ApiError(
      412,
      "plan.md is required — run /speckit.plan with this featureSlug first",
      "SPECKIT_GATE_UNMET",
      { required: "planGate" },
    );
    expect(describeSpecKitError(err)).toBe(
      "This feature has no plan.md yet. Run /speckit.plan on it first.",
    );
    expect(
      describeSpecKitError(new ApiError(412, "x", "SPECKIT_GATE_UNMET", { required: "tasksGate" })),
    ).toMatch(/no tasks\.md yet/);
  });

  it("falls back to the server message for an unknown gate", () => {
    expect(describeSpecKitError(new ApiError(412, "raw gate text", "SPECKIT_GATE_UNMET", {}))).toBe(
      "raw gate text",
    );
  });

  it("replaces the legacy command names in known errors", () => {
    expect(
      describeSpecKitError(
        new ApiError(409, "Run /specify first — no spec.md found", "SPEC_KIT_PLAN_NEEDS_SPEC"),
      ),
    ).toBe("There is no spec.md yet. Run /speckit.specify first.");
    expect(
      describeSpecKitError(
        new ApiError(409, "Run /specify, /plan, and /tasks", "SPEC_KIT_ANALYZE_INCOMPLETE"),
      ),
    ).toMatch(/^\/speckit\.analyze needs/);
  });

  it("turns a serialized validation-issue array into a sentence", () => {
    const zod = JSON.stringify(
      [
        {
          code: "too_big",
          maximum: 200000,
          path: ["content"],
          message: "String must contain at most 200000 character(s)",
        },
        { code: "custom", path: [], message: "Body is invalid" },
      ],
      null,
      2,
    );
    expect(describeSpecKitError(new ApiError(400, zod, "BAD_REQUEST"))).toBe(
      "The request was not accepted — content: String must contain at most 200000 character(s); Body is invalid.",
    );
  });

  it("keeps a plain 400 message, and anything that only looks like JSON", () => {
    expect(describeSpecKitError(new ApiError(400, "Bad slug", "BAD_REQUEST"))).toBe("Bad slug");
    expect(describeSpecKitError(new ApiError(400, "[not json", "BAD_REQUEST"))).toBe("[not json");
    expect(describeSpecKitError(new ApiError(400, "[]", "BAD_REQUEST"))).toBe("[]");
    expect(describeSpecKitError(new ApiError(400, "[{}]", "BAD_REQUEST"))).toBe(
      "The request was not accepted — is not valid.",
    );
  });

  it("never shows a non-API error's text", () => {
    expect(describeSpecKitError(new Error("TypeError: x is undefined"))).toBe(
      "The Spec Kit operation failed. Please try again.",
    );
  });
});

describe("isNoProjectAccess", () => {
  it("is true for 404 and 403 only", () => {
    expect(isNoProjectAccess(new ApiError(404, "Project not found"))).toBe(true);
    expect(isNoProjectAccess(new ApiError(403, "Forbidden"))).toBe(true);
    expect(isNoProjectAccess(new ApiError(500, "boom"))).toBe(false);
    expect(isNoProjectAccess(null)).toBe(false);
  });
});

describe("handoff storage", () => {
  afterEach(() => window.sessionStorage.clear());

  it("round-trips per project and forgets on null", () => {
    saveHandoff("p1", { context: ["specs/001-a/spec.md"], feature: "001-a" });
    expect(loadHandoff("p1")).toEqual({ context: ["specs/001-a/spec.md"], feature: "001-a" });
    expect(loadHandoff("p2")).toBeNull();
    saveHandoff("p1", null);
    expect(loadHandoff("p1")).toBeNull();
  });

  it("ignores a malformed entry", () => {
    window.sessionStorage.setItem("metis:spec-kit-handoff:p1", "{oops");
    expect(loadHandoff("p1")).toBeNull();
    window.sessionStorage.setItem("metis:spec-kit-handoff:p1", JSON.stringify({ context: [1] }));
    expect(loadHandoff("p1")).toBeNull();
    window.sessionStorage.setItem(
      "metis:spec-kit-handoff:p1",
      JSON.stringify({ context: ["a"], feature: 7 }),
    );
    expect(loadHandoff("p1")).toEqual({ context: ["a"], feature: null });
  });
});
