#!/bin/sh
# ==============================================================================
# Generate server/prisma/postgres/schema.prisma from server/prisma/schema.prisma
# (issue #390 — schema-duality cleanup).
#
# The SQLite schema (`schema.prisma`) is the SINGLE SOURCE OF TRUTH. The
# Postgres schema is mechanically derived by:
#
#   1. Swapping the datasource block from `provider = "sqlite"` to
#      `provider = "postgresql"`.
#   2. Replacing the leading comment header so it's clear this file is
#      autogenerated and must NOT be edited by hand.
#
# Everything else stays byte-identical. The schemas use only types portable
# across SQLite + Postgres (no `Json` columns — JSON blobs are stored as
# TEXT/String and serialised by the application via `JSON.stringify` /
# `JSON.parse`, matching the existing route-handler conventions and the
# `JSON-as-String` model the SQLite migrations have always required).
#
# Idempotent. Run `pnpm db:gen-postgres` after editing `schema.prisma`.
# CI parity guard: `git diff --exit-code server/prisma/postgres/schema.prisma`
# after running this script.
# ==============================================================================

set -e

SRC="server/prisma/schema.prisma"
DST="server/prisma/postgres/schema.prisma"

if [ ! -f "${SRC}" ]; then
  echo "[gen-postgres] ${SRC} not found — run from repo root" >&2
  exit 1
fi

# Header — first 3 lines of the canonical schema are a comment block we
# replace with the autogen warning + provenance pointer.
HEADER="// METIS Prisma schema — PROD (PostgreSQL).
//
// AUTOGENERATED from schema.prisma by scripts/gen-postgres-schema.sh
// (issue #390). DO NOT EDIT BY HAND. Update schema.prisma and run
// \`pnpm db:gen-postgres\` to regenerate this file.
"

# tail -n +4 strips the source's first three comment lines (the
# 'METIS Prisma schema — DEV (SQLite)' header). The sed swaps the provider.
{
  printf "%s" "${HEADER}"
  tail -n +4 "${SRC}" | sed 's/^  provider = "sqlite"$/  provider = "postgresql"/'
} > "${DST}.tmp"

mv "${DST}.tmp" "${DST}"

# Sanity check: the dst file MUST contain a postgres datasource and MUST NOT
# contain a sqlite datasource. Fail loud if the substitution didn't happen.
if ! grep -q '^  provider = "postgresql"$' "${DST}"; then
  echo "[gen-postgres] FATAL: provider substitution failed" >&2
  exit 1
fi
if grep -q '^  provider = "sqlite"$' "${DST}"; then
  echo "[gen-postgres] FATAL: sqlite provider still present in generated postgres schema" >&2
  exit 1
fi

echo "[gen-postgres] regenerated ${DST} from ${SRC}"
