#Requires -Version 5.1
<#
.SYNOPSIS
  Generate server/prisma/postgres/schema.prisma from server/prisma/schema.prisma
  (issue #390). Windows / PowerShell port of gen-postgres-schema.sh.

.DESCRIPTION
  The SQLite schema (schema.prisma) is the SINGLE SOURCE OF TRUTH. The Postgres
  schema is mechanically derived by:
    1. Swapping the datasource provider from "sqlite" to "postgresql".
    2. Replacing the leading comment header with an autogen warning.
  Everything else stays byte-identical.

  Idempotent. Run after editing schema.prisma.
  CI parity guard:
    git diff --exit-code server/prisma/postgres/schema.prisma
#>
[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Src = 'server/prisma/schema.prisma'
$Dst = 'server/prisma/postgres/schema.prisma'

if (-not (Test-Path -LiteralPath $Src -PathType Leaf)) {
  Write-Error "[gen-postgres] $Src not found - run from repo root"
}

# Header replacing the source's first three comment lines. Built byte-for-byte
# identical to scripts/gen-postgres-schema.sh so the generated file is the same
# regardless of which generator ran (keeps the CI `git diff --exit-code` parity
# guard green). The em-dash is constructed via [char]0x2014 so this script's own
# encoding (Windows PowerShell 5.1 reads a BOM-less file as ANSI) cannot corrupt
# the output.
$emDash = [char]0x2014
$headerLines = @(
  "// METIS Prisma schema $emDash PROD (PostgreSQL)."
  '//'
  '// AUTOGENERATED from schema.prisma by scripts/gen-postgres-schema.sh'
  '// (issue #390). DO NOT EDIT BY HAND. Update schema.prisma and run'
  '// `pnpm db:gen-postgres` to regenerate this file.'
)
$Header = ($headerLines -join "`n") + "`n"

# Read the source, drop the first 3 comment-header lines (matching `tail -n +4`),
# then swap the datasource provider line. `-Encoding UTF8` is REQUIRED: Windows
# PowerShell 5.1 defaults to ANSI, which would mangle the UTF-8 em-dashes in the
# schema comments and break byte-parity with the .sh generator.
$srcLines = Get-Content -LiteralPath $Src -Encoding UTF8
$body = $srcLines | Select-Object -Skip 3 | ForEach-Object {
  $_ -replace '^  provider = "sqlite"$', '  provider = "postgresql"'
}

# Join with LF to match the byte-stable .gitattributes policy for *.prisma
# (text eol=lf) and the original POSIX script output.
$out = $Header + (($body -join "`n") + "`n")
$tmp = "$Dst.tmp"
[System.IO.File]::WriteAllText((Join-Path (Get-Location) $tmp), $out)
Move-Item -LiteralPath $tmp -Destination $Dst -Force

# Sanity checks: dst MUST contain a postgres datasource and MUST NOT contain a
# sqlite datasource. Fail loud if the substitution did not happen.
$dstContent = Get-Content -LiteralPath $Dst
if (-not ($dstContent | Select-String -Pattern '^  provider = "postgresql"$' -Quiet)) {
  Write-Error '[gen-postgres] FATAL: provider substitution failed'
}
if ($dstContent | Select-String -Pattern '^  provider = "sqlite"$' -Quiet) {
  Write-Error '[gen-postgres] FATAL: sqlite provider still present in generated postgres schema'
}

Write-Host "[gen-postgres] regenerated $Dst from $Src"
