/**
 * Write a corpus's `snapshot-manifest.json` — the provenance record that lets
 * `corpus.test.ts` check a snapshot against the commit it DECLARES, rather than
 * against whatever `server/src/lib/**` happens to contain today (PR #1174 review).
 *
 * ## Why this file exists rather than a `git show` in the test
 *
 * The first cut of #1157 asserted the snapshot was byte-identical to the LIVE
 * working tree. That is the wrong invariant twice over:
 *
 *  - It fails when `main` moves on. Epic #1156's sub-issue C (#1159) edits
 *    `tokenizeCode` in `code-graph/hybrid-search.ts`, which is snapshotted here, so
 *    that test would have gone red on an unrelated PR — and the reflexive repair is
 *    to resync the snapshot, which silently changes the corpus mid-epic and destroys
 *    the before/after comparison the corpus exists to provide.
 *  - It never actually checked the `snapshotCommit` line, which is the claim a
 *    reader relies on.
 *
 * A `git show <snapshotCommit>:<path>` in the test would check the right thing but
 * `actions/checkout` in `.github/workflows/ci.yml` sets no `fetch-depth`, so CI runs
 * on a depth-1 clone where that object does not exist. The check would degrade to a
 * permanent silent skip. A committed manifest is verified on every run with no git
 * at all, and the git cross-check below still runs wherever history is present.
 *
 * ## What is recorded
 *
 * Every file under `repo/` and `schema/`. Entries with a `source` are FULL-FILE
 * copies and their hash is read from `git show <snapshotCommit>:<source>` — so the
 * manifest cannot launder drift that is already in the snapshot. Entries with
 * `source: null` (the `schema.prisma` EXCERPT, and anything in
 * {@link REDACTED_SNAPSHOT_FILES}) are hashed from the committed file: drift in them
 * is still caught, but no provenance claim is made for them, because an excerpt — or
 * a file a redaction has deliberately moved away from its source — is not
 * byte-identical to any file at any commit.
 *
 *   pnpm --filter @metis/server exec tsx scripts/write-corpus-snapshot-manifest.ts \
 *     embedretrieval-02-nl-to-code
 */
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  corpusDir,
  DEFAULT_CORPUS_ID,
  SNAPSHOT_MANIFEST_FILE,
  SNAPSHOT_SUBTREES,
  snapshotSourceFor,
  type SnapshotManifest,
} from "../src/lib/eval/embed-retrieval/corpus.js";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

const sha256 = (buf: Buffer | string): string => createHash("sha256").update(buf).digest("hex");

async function listFiles(dir: string, base = ""): Promise<string[]> {
  const out: string[] = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries.sort((a, b) => (a.name < b.name ? -1 : 1))) {
    const rel = base ? `${base}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...(await listFiles(path.join(dir, entry.name), rel)));
    else out.push(rel);
  }
  return out;
}

async function main(): Promise<void> {
  const corpusId = process.argv[2] ?? DEFAULT_CORPUS_ID;
  const dir = corpusDir(corpusId);
  const spec = JSON.parse(await fs.readFile(path.join(dir, "queries.json"), "utf8"));
  const snapshotCommit: string = spec.snapshotCommit;
  if (!snapshotCommit) throw new Error(`${corpusId}/queries.json declares no snapshotCommit`);

  // Top-level snapshot subtrees. `repo/sql-lineage` is nested inside `repo` and is
  // picked up by the walk, so only the roots are listed here. A corpus that does not
  // use a subtree simply has no such directory and `listFiles` returns nothing.
  const rels: string[] = [];
  for (const top of SNAPSHOT_SUBTREES) {
    rels.push(...(await listFiles(path.join(dir, top), top)));
  }
  rels.sort();

  const files: SnapshotManifest["files"] = {};
  for (const rel of rels) {
    const source = snapshotSourceFor(rel);
    if (source) {
      // Read the hash FROM GIT, never from the snapshot file — that is the whole
      // point. Regenerating from the snapshot would make the manifest agree with
      // drift instead of catching it.
      const atCommit = execFileSync("git", ["show", `${snapshotCommit}:${source}`], {
        cwd: REPO_ROOT,
        maxBuffer: 64 * 1024 * 1024,
      });
      files[rel] = { sha256: sha256(atCommit), source };
    } else {
      files[rel] = { sha256: sha256(await fs.readFile(path.join(dir, rel))), source: null };
    }
  }

  const manifest: SnapshotManifest = {
    corpusId,
    snapshotCommit,
    algorithm: "sha256",
    note:
      "Generated by server/scripts/write-corpus-snapshot-manifest.ts. Entries with a " +
      "`source` are hashed from `git show <snapshotCommit>:<source>`, NOT from the " +
      "snapshot file, so this manifest cannot agree with drift already present in the " +
      "snapshot. Entries with `source: null` are excerpts hashed from the committed " +
      "file: drift in them is caught, but no provenance claim is made for them.",
    files,
  };

  const out = path.join(dir, SNAPSHOT_MANIFEST_FILE);
  await fs.writeFile(out, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  // eslint-disable-next-line no-console
  console.log(`Wrote ${out} — ${Object.keys(files).length} files at ${snapshotCommit}`);
}

await main();
