{{- if .Values.embeddings.enabled -}}
{{ include "metis.componentDeployment" (dict "root" . "component" .Values.embeddings "name" "embeddings") }}
---
{{ include "metis.componentService" (dict "root" . "component" .Values.embeddings "name" "embeddings") }}
{{- end }}
