{{- if .Values.server.enabled -}}
{{ include "metis.componentDeployment" (dict "root" . "component" .Values.server "name" "server") }}
---
{{ include "metis.componentService" (dict "root" . "component" .Values.server "name" "server") }}
{{- end }}
