import { execSync } from "node:child_process";
import { readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

/**
 * Issue #390 — schema-duality cleanup.
 *
 * The Postgres schema is autogenerated from the SQLite schema by
 * `scripts/gen-postgres-schema.sh`. Both schemas MUST stay byte-identical
 * outside the documented diff (header comment + datasource block) so that:
 *
 *   - the same Prisma client + TypeScript types compile against both providers;
 *   - JSON-as-TEXT route handlers (skill-directories, aclSubjects, etc.) work
 *     unchanged on both sqlite and postgres;
 *   - any new model added to schema.prisma is automatically reflected in the
 *     postgres mirror — no chance of silent drift.
 *
 * This test fails loud if a developer hand-edits schema.postgres.prisma or
 * adds a model/field to schema.prisma without re-running `pnpm db:gen-postgres`.
 */

const repoRoot = resolve(__dirname, "..", "..");
const sqlitePath = resolve(repoRoot, "server/prisma/schema.prisma");
const postgresPath = resolve(repoRoot, "server/prisma/postgres/schema.prisma");
const generatorScript = resolve(repoRoot, "scripts/gen-postgres-schema.sh");

function stripDatasource(source: string): string {
  // Drop the leading comment block (lines starting `//` until the first
  // non-comment line) plus the entire `datasource db { ... }` block.
  const withoutHeader = source.replace(/^(\/\/[^\n]*\n)+/, "");
  return withoutHeader.replace(/datasource\s+db\s*\{[^}]+\}\s*/m, "");
}

describe("issue #390 — schema parity guard", () => {
  it("postgres schema is byte-identical to sqlite schema outside the datasource block", () => {
    const sqlite = readFileSync(sqlitePath, "utf-8");
    const postgres = readFileSync(postgresPath, "utf-8");
    expect(stripDatasource(postgres)).toEqual(stripDatasource(sqlite));
  });

  it("regenerating the postgres schema produces no diff", () => {
    // If a developer edits schema.prisma, the postgres mirror must be
    // regenerated. Running the generator should be a no-op when the mirror
    // is already up-to-date.
    execSync(`bash ${generatorScript}`, { cwd: repoRoot, stdio: "pipe" });
    const postgresAfter = readFileSync(postgresPath, "utf-8");
    const sqlite = readFileSync(sqlitePath, "utf-8");
    expect(stripDatasource(postgresAfter)).toEqual(stripDatasource(sqlite));
    expect(postgresAfter).toMatch(/provider = "postgresql"/);
    expect(postgresAfter).not.toMatch(/provider = "sqlite"/);
  });

  it("postgres baseline migration exists and has the same table count as the schema", () => {
    const initSql = readFileSync(
      resolve(repoRoot, "server/prisma/postgres/migrations/00000000000000_init/migration.sql"),
      "utf-8",
    );
    const sqlite = readFileSync(sqlitePath, "utf-8");
    const modelCount = (sqlite.match(/^model\s+\w+\s*\{/gm) ?? []).length;
    const createTableCount = (initSql.match(/^CREATE TABLE /gm) ?? []).length;
    // The comparison below is `>=`, so it is VACUOUS when the left-hand regex
    // matches nothing: at `modelCount === 0` it passes for every possible
    // baseline, including an empty one. Measured (#1215) by evaluating both
    // regexes against mutated sources — the real schema yields 156/156, an empty
    // `migration.sql` yields 0 tables and correctly FAILS, and a `schema.prisma`
    // with no `model` blocks yields 0 and passes whatever the baseline holds.
    // `readFileSync` throws on an absent file, so this guard pins the other half:
    // present, readable, and parsed to nothing.
    expect(modelCount).toBeGreaterThan(0);
    // Every model in the schema MUST produce a CreateTable in the baseline.
    // Allows a small slack for join-table edge cases (Prisma generates implicit
    // m:n join tables that may not appear as `model` blocks).
    expect(createTableCount).toBeGreaterThanOrEqual(modelCount);
  });
});

/**
 * Issue #556 — the Postgres migration HISTORY must apply from an empty database
 * via `prisma migrate deploy`.
 *
 * The `00000000000000_init` baseline is a CUMULATIVE snapshot of the full
 * current schema: the schema-parity workflow APPENDS every new table/column/
 * index to it so its `CREATE TABLE` count keeps pace with the model count
 * (the guard above). But each later incremental migration ALSO contains the
 * same DDL it added — so replaying the full chain on a clean Postgres used to
 * collide (`42701 column ... already exists`, first hit
 * `suggested_connectors.username`). This stayed latent until #539 made Postgres
 * a real runtime target.
 *
 * The fix makes every *incremental* migration's structural DDL idempotent so it
 * no-ops against the baseline-created schema. This static guard fails loud if a
 * future incremental Postgres migration reintroduces NON-idempotent structural
 * DDL — the recurrence vector, since the baseline keeps being cumulatively
 * edited. The live `prisma migrate deploy`-from-empty proof runs in the
 * `postgres-migrate-deploy` CI job against a real `postgres:16-alpine`.
 */
describe("issue #556 — postgres migration history applies from scratch", () => {
  const migrationsDir = resolve(repoRoot, "server/prisma/postgres/migrations");

  // The cumulative snapshot baseline is applied to an EMPTY database, so its
  // bare CREATE statements are correct and intentionally exempt.
  const BASELINE = "00000000000000_init";

  function incrementalMigrations(): { name: string; sql: string }[] {
    return readdirSync(migrationsDir, { withFileTypes: true })
      .filter((d) => d.isDirectory() && d.name !== BASELINE)
      .map((d) => ({
        name: d.name,
        sql: readFileSync(resolve(migrationsDir, d.name, "migration.sql"), "utf-8"),
      }))
      .sort((a, b) => a.name.localeCompare(b.name));
  }

  /** Strip `--` line comments and `$$ ... $$` dollar-quoted blocks (DO blocks /
   *  function bodies are already idempotent guards and may legitimately contain
   *  bare DDL inside an EXECUTE string), then split on `;`. */
  function structuralStatements(sql: string): string[] {
    const noDollar = sql.replace(/\$(\w*)\$[\s\S]*?\$\1\$/g, " ");
    const noComments = noDollar.replace(/--[^\n]*/g, "");
    return noComments
      .split(";")
      .map((s) => s.trim())
      .filter(Boolean);
  }

  it("has the known incremental migrations (sanity)", () => {
    const names = incrementalMigrations().map((m) => m.name);
    expect(names.length).toBeGreaterThan(0);
    expect(names).toContain("20260517000000_suggested_connector_credentials");
  });

  it("every incremental CREATE TABLE is `IF NOT EXISTS`", () => {
    for (const { name, sql } of incrementalMigrations()) {
      for (const stmt of structuralStatements(sql)) {
        if (/^CREATE\s+TABLE\b/i.test(stmt)) {
          expect(stmt, `${name}: ${stmt.slice(0, 80)}`).toMatch(
            /^CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\b/i,
          );
        }
      }
    }
  });

  it("every incremental CREATE [UNIQUE] INDEX is `IF NOT EXISTS`", () => {
    for (const { name, sql } of incrementalMigrations()) {
      for (const stmt of structuralStatements(sql)) {
        if (/^CREATE\s+(UNIQUE\s+)?INDEX\b/i.test(stmt)) {
          expect(stmt, `${name}: ${stmt.slice(0, 80)}`).toMatch(
            /^CREATE\s+(UNIQUE\s+)?INDEX\s+IF\s+NOT\s+EXISTS\b/i,
          );
        }
      }
    }
  });

  it("every incremental ADD COLUMN clause is `IF NOT EXISTS`", () => {
    for (const { name, sql } of incrementalMigrations()) {
      for (const stmt of structuralStatements(sql)) {
        if (!/^ALTER\s+TABLE\b/i.test(stmt)) continue;
        // Inspect each `ADD COLUMN` occurrence within the (possibly
        // multi-clause) ALTER TABLE statement.
        const addColumns = stmt.match(/ADD\s+COLUMN\b(?:\s+IF\s+NOT\s+EXISTS\b)?/gi) ?? [];
        for (const clause of addColumns) {
          expect(clause.replace(/\s+/g, " "), `${name}: ${stmt.slice(0, 80)}`).toMatch(
            /ADD COLUMN IF NOT EXISTS/i,
          );
        }
      }
    }
  });

  it("every incremental ADD CONSTRAINT is wrapped in an existence guard (no bare ADD CONSTRAINT)", () => {
    // Bare `ALTER TABLE ... ADD CONSTRAINT` (FKs) has no `IF NOT EXISTS` in
    // Postgres, so it must live inside a `$$ ... $$` DO-block guard — which
    // structuralStatements() strips. Any ADD CONSTRAINT still visible after
    // stripping dollar-quoted blocks is therefore an UNGUARDED collision risk.
    for (const { name, sql } of incrementalMigrations()) {
      for (const stmt of structuralStatements(sql)) {
        expect(
          /\bADD\s+CONSTRAINT\b/i.test(stmt),
          `${name}: unguarded ADD CONSTRAINT — wrap it in a pg_constraint existence DO-block: ${stmt.slice(0, 90)}`,
        ).toBe(false);
      }
    }
  });
});
